from enum import Enum

class ConfigRef(Enum):
    img_ref_phasor_all_vll = r".\image_ref\11.img_ref_phasor_all_vll.png"
    img_ref_phasor_all_vll_none = r".\image_ref\11.img_ref_phasor_all_vll_none.png"
    img_ref_phasor_all_vln = r".\image_ref\12.img_ref_phasor_all_vln.png"
    img_ref_phasor_all_vln_none = r".\image_ref\12.img_ref_phasor_all_vln_none.png"
    img_ref_phasor_vol_vll = r".\image_ref\13.img_ref_phasor_vol_vll.png"
    img_ref_phasor_vol_vll_none = r".\image_ref\13.img_ref_phasor_vol_vll_none.png"
    img_ref_phasor_vol_vln = r".\image_ref\14.img_ref_phasor_vol_vln.png"
    img_ref_phasor_vol_vln_none = r".\image_ref\14.img_ref_phasor_vol_vln_none.png"
    img_ref_phasor_curr_vll = r".\image_ref\15.img_ref_phasor_curr_vll.png"
    img_ref_phasor_curr_vll_none = r".\image_ref\15.img_ref_phasor_curr_vll_none.png"
    img_ref_phasor_curr_vln = r".\image_ref\16.img_ref_phasor_curr_vln.png"
    img_ref_phasor_curr_vln_none = r".\image_ref\16.img_ref_phasor_curr_vln_none.png"
    img_ref_phasor_na_vll = r".\image_ref\17.img_ref_phasor_na_vll.png"
    img_ref_phasor_na_vln = r".\image_ref\17.img_ref_phasor_na_vln.png"
    img_ref_harmonics_vol_3p4w = r".\image_ref\21.img_ref_harmonics_vol_3p4w.png"
    img_ref_harmonics_vol_3p4w_none = r".\image_ref\21.img_ref_harmonics_vol_3p4w_none.png"
    img_ref_harmonics_curr = r".\image_ref\22.img_ref_harmonics_curr.png"
    img_ref_harmonics_curr_none = r".\image_ref\22.img_ref_harmonics_curr_none.png"
    img_ref_harmonics_vol_fund = r".\image_ref\23.img_ref_harmonics_vol_fund.png"
    img_ref_harmonics_vol_fund_none = r".\image_ref\23.img_ref_harmonics_vol_fund_none.png"
    img_ref_harmonics_vol_rms = r".\image_ref\24.img_ref_harmonics_vol_rms.png"
    img_ref_harmonics_vol_rms_none = r".\image_ref\24.img_ref_harmonics_vol_rms_none.png"
    img_ref_harmonics_curr_fund = r".\image_ref\25.img_ref_harmonics_curr_fund.png"
    img_ref_harmonics_curr_fund_none = r".\image_ref\25.img_ref_harmonics_curr_fund_none.png"
    img_ref_harmonics_curr_rms = r".\image_ref\26.img_ref_harmonics_curr_rms.png"
    img_ref_harmonics_curr_rms_none = r".\image_ref\26.img_ref_harmonics_curr_rms_none.png"
    img_ref_waveform_all = r".\image_ref\41.img_ref_waveform_all.png"
    img_ref_waveform_all_none = r".\image_ref\42.img_ref_waveform_all_none.png"